export interface AgentDef {
  id: string;
  name: string;
  emoji: string;
  role: string;
  description: string;
  category: "copywriting" | "content" | "branding";
  available: boolean;
}

export const AGENT_CATEGORIES = [
  { id: "copywriting" as const, label: "Copywriting", emoji: "✍️", color: "from-purple-500 to-pink-500" },
  { id: "content" as const, label: "Conteúdo & Social", emoji: "📱", color: "from-blue-500 to-cyan-500" },
  { id: "branding" as const, label: "Branding & Estratégia", emoji: "💎", color: "from-amber-500 to-orange-500" },
] as const;

export const AGENTS: AgentDef[] = [
  // Copywriting
  {
    id: "sales-page",
    name: "Arquiteto de Vendas",
    emoji: "🏗️",
    role: "Especialista em Páginas de Vendas",
    description: "Cria páginas de vendas de alta conversão com narrativa persuasiva, provas sociais e CTAs estratégicos.",
    category: "copywriting",
    available: true,
  },
  {
    id: "vsl-writer",
    name: "Roteirista VSL",
    emoji: "🎬",
    role: "Especialista em Video Sales Letters",
    description: "Produz roteiros cinematográficos para VSLs de 15 a 60 minutos com gatilhos emocionais e estrutura narrativa.",
    category: "copywriting",
    available: true,
  },
  {
    id: "email-sequence",
    name: "Estrategista de E-mails",
    emoji: "📧",
    role: "Especialista em Sequências de E-mail",
    description: "Cria sequências de e-mail automatizadas para nutrição, lançamento e recuperação de carrinho.",
    category: "copywriting",
    available: false,
  },
  {
    id: "email-subjects",
    name: "Assuntos de E-mails",
    emoji: "✉️",
    role: "Especialista em Títulos de E-mail",
    description: "Cria títulos de e-mail que disparam taxas de abertura com micro-histórias irresistíveis e preheaders estratégicos.",
    category: "copywriting",
    available: true,
  },
  // Content & Social
  {
    id: "carousel-creator",
    name: "Designer de Carrosséis",
    emoji: "🎠",
    role: "Especialista em Conteúdo Visual",
    description: "Cria roteiros de carrosséis para Instagram e LinkedIn com hooks irresistíveis e CTAs de engajamento.",
    category: "content",
    available: true,
  },
  {
    id: "video-script",
    name: "Roteirista de Reels",
    emoji: "🎥",
    role: "Especialista em Vídeos Curtos",
    description: "Produz scripts para Reels, TikTok e Shorts com ganchos nos primeiros 3 segundos.",
    category: "content",
    available: false,
  },
  {
    id: "youtube-titles",
    name: "Ângulos e Títulos YouTube",
    emoji: "▶️",
    role: "Especialista em Títulos e CTR",
    description: "Gera ângulos, variações e títulos otimizados para maximizar CTR e performance no YouTube.",
    category: "content",
    available: true,
  },
  {
    id: "newsletter-writer",
    name: "Escritor de Newsletter",
    emoji: "📰",
    role: "Especialista em Storytelling para Newsletters",
    description: "Transforma ideias em narrativas longas e reflexivas para newsletters, com fluxo modular de Introdução, Desenvolvimento e Conclusão.",
    category: "content",
    available: true,
  },
  {
    id: "ad-funnel",
    name: "Funil de Anúncios",
    emoji: "🔻",
    role: "Especialista em Funil de Consciência",
    description: "Cria sequência completa de anúncios baseada nos 5 Níveis de Consciência de Schwartz, do insciente à conversão.",
    category: "copywriting",
    available: true,
  },
  {
    id: "text-structure",
    name: "Estrutura de Textos Memoráveis",
    emoji: "🗺️",
    role: "Especialista em Estruturação Estratégica",
    description: "Usa o método GPS da Escrita para criar estruturas de texto poderosas, mapeando da conclusão ao título.",
    category: "content",
    available: true,
  },
  {
    id: "big-ideas",
    name: "Big Ideas para Newsletter",
    emoji: "💡",
    role: "Especialista em Conceitos Memoráveis",
    description: "Transforma ideias brutas em big ideas estratégicas que geram impacto imediato e conexão emocional.",
    category: "content",
    available: true,
  },
  // Branding & Strategy
  {
    id: "brand-voice",
    name: "Arquiteto de Marca",
    emoji: "🎭",
    role: "Especialista em Tom de Voz",
    description: "Define o posicionamento, tom de voz e identidade verbal da marca com guidelines aplicáveis.",
    category: "branding",
    available: true,
  },
  {
    id: "naming-expert",
    name: "Naming Expert",
    emoji: "💡",
    role: "Especialista em Naming",
    description: "Gera nomes criativos para produtos, marcas e ofertas com análise de disponibilidade e sonoridade.",
    category: "branding",
    available: false,
  },
  {
    id: "persuasive-premise",
    name: "Premissa Persuasiva",
    emoji: "💎",
    role: "Especialista em Premissa Única",
    description: "Define a única crença que, se aceita pelo cliente, torna a compra do seu produto o único caminho lógico.",
    category: "branding",
    available: true,
  },
  {
    id: "high-value-compass",
    name: "Bússola do Cliente de Alto Valor",
    emoji: "🧭",
    role: "Especialista em Segmentação de Alto Ticket",
    description: "Identifica clientes ideais de alto valor usando a metodologia da bússola (6 direções) e o Axioma 41-39-20.",
    category: "branding",
    available: true,
  },
  {
    id: "content-calendar",
    name: "Calendário de Conteúdo",
    emoji: "📅",
    role: "Especialista em Planejamento de Conteúdo",
    description: "Cria calendário estratégico com 15 posts conectados à jornada do cliente, equilibrando valor e conversão.",
    category: "content",
    available: true,
  },
  {
    id: "twitter-content",
    name: "Conteúdo para Twitter/X",
    emoji: "𝕏",
    role: "Especialista em Conteúdo para Twitter/X",
    description: "Cria tweets, threads e frases que engajam, educam e vendem usando frameworks estratégicos por estágio de funil.",
    category: "content",
    available: true,
  },
  {
    id: "youtube-description",
    name: "Descrição YouTube",
    emoji: "📝",
    role: "Especialista em SEO para YouTube",
    description: "Cria descrições otimizadas para SEO que ajudam seus vídeos a ranquear melhor em buscas específicas no YouTube.",
    category: "content",
    available: true,
  },
  // Storytelling (special - content category)
  {
    id: "storytelling-adapter",
    name: "Adaptador de Storytelling",
    emoji: "📖",
    role: "Especialista em Narrativa Persuasiva",
    description: "Transforma qualquer conteúdo em uma narrativa mais poderosa usando frameworks clássicos de storytelling.",
    category: "content",
    available: true,
  },
  {
    id: "universal-adapter",
    name: "Adaptador Universal",
    emoji: "🔄",
    role: "Especialista em Replicação Estrutural",
    description: "Replica a arquitetura persuasiva de qualquer criativo validado, adaptando o conteúdo ao DNA da sua campanha.",
    category: "copywriting",
    available: true,
  },
  {
    id: "content-to-ad",
    name: "Conteúdo em Anúncio",
    emoji: "📢",
    role: "Especialista em Conversão de Conteúdo para Ads",
    description: "Transforma conteúdo orgânico validado em anúncios de alta conversão para Meta Ads com 5 hooks testáveis.",
    category: "copywriting",
    available: true,
  },
  {
    id: "ad-angles",
    name: "Ângulos de Anúncios",
    emoji: "🎯",
    role: "Especialista em Ângulos Criativos",
    description: "Transforma um anúncio em 5 abordagens estratégicas únicas para maximizar performance no Meta Ads.",
    category: "copywriting",
    available: true,
  },
  {
    id: "writing-analysis",
    name: "Análise de Escrita",
    emoji: "🔍",
    role: "Especialista em Análise Estilística",
    description: "Decifra e replica qualquer estilo de escrita com precisão, revelando padrões de tom, estrutura e elementos distintivos.",
    category: "branding",
    available: true,
  },
];
