export interface AgentDef {
  id: string;
  name: string;
  emoji: string;
  role: string;
  description: string;
  category: "guided" | "ideation" | "copywriting" | "content" | "products" | "branding";
  available: boolean;
  freeAccess?: boolean; // true = available on free plan
}

// IDs of agents available on free plan (3 basic)
export const FREE_AGENT_IDS = ["icp-profile", "sales-page", "carousel-creator", "venda-direta-orchestrator", "oferta-usp"];

export const AGENT_CATEGORIES = [
  { id: "guided" as const, label: "Fluxo Guiado V1", emoji: "🚀", color: "from-violet-500 to-purple-500" },
  { id: "ideation" as const, label: "Ideação & Estratégia", emoji: "💡", color: "from-yellow-500 to-amber-500" },
  { id: "copywriting" as const, label: "Copywriting", emoji: "✍️", color: "from-purple-500 to-pink-500" },
  { id: "content" as const, label: "Conteúdo & Social", emoji: "📱", color: "from-blue-500 to-cyan-500" },
  { id: "products" as const, label: "Produtos & Ofertas", emoji: "📦", color: "from-emerald-500 to-teal-500" },
  { id: "branding" as const, label: "Branding & Posicionamento", emoji: "🎭", color: "from-amber-500 to-orange-500" },
] as const;

export const AGENTS: AgentDef[] = [
  // ── Fluxo Guiado V1 ──
  {
    id: "venda-direta-orchestrator",
    name: "Orquestrador — Venda Direta",
    emoji: "🚀",
    role: "Orquestrador de Campanha de Venda Direta",
    description: "Transforma seu objetivo em um plano executável de 8–12 passos com agentes conectados. O ponto de partida ideal para qualquer campanha.",
    category: "guided",
    available: true,
    freeAccess: true,
  },
  {
    id: "icp-profile",
    name: "Avatar / ICP",
    emoji: "🎯",
    role: "Especialista em Mapeamento de Cliente Ideal",
    description: "Cria perfis detalhados do cliente ideal usando o segredo EJACA e Axioma 41-39-20 para você entender seu cliente melhor do que ele mesmo.",
    category: "guided",
    available: true,
    freeAccess: true,
  },
  {
    id: "oferta-usp",
    name: "Oferta & USP",
    emoji: "💰",
    role: "Especialista em Ofertas e Proposta Única de Vendas",
    description: "Gera oferta completa com promessa, ICP, mecanismo, benefícios, USP, objeções mapeadas e CTA — tudo pronto para usar.",
    category: "guided",
    available: true,
    freeAccess: true,
  },
  {
    id: "proof-builder",
    name: "Proof Builder",
    emoji: "🛡️",
    role: "Especialista em Provas sem Depoimentos",
    description: "Cria provas utilizáveis sem cases: bullets de credibilidade, roteiros de demo (60s e 3min), e formas de coletar prova em 7 dias.",
    category: "guided",
    available: true,
  },
  {
    id: "sales-page",
    name: "Landing de Vendas",
    emoji: "🏗️",
    role: "Especialista em Páginas de Vendas",
    description: "Cria páginas de vendas de alta conversão com narrativa persuasiva, provas sociais e CTAs estratégicos.",
    category: "guided",
    available: true,
  },
  {
    id: "ads-studio",
    name: "Ads Studio",
    emoji: "📣",
    role: "Especialista em Pacotes de Anúncios",
    description: "Gera matriz de 6 ângulos com 12+ anúncios completos (hook, texto, headline, CTA) prontos para Meta Ads.",
    category: "guided",
    available: true,
  },
  {
    id: "audit-premium",
    name: "Auditoria Premium",
    emoji: "🩺",
    role: "Auditor de Copy com Score e Revisão",
    description: "Audita qualquer texto com score 0-10 em 6 dimensões, checklist prioritário e (Pro) texto revisado + 3 variações seguras.",
    category: "guided",
    available: true,
  },

  // ── Ideação & Estratégia ──
  // icp-profile moved to guided category
  {
    id: "low-ticket-ideas",
    name: "Ideias de Produto Low Ticket",
    emoji: "💡",
    role: "Estrategista de Produtos Low Ticket",
    description: "Gera 10 ideias de produtos low ticket pelo Framework de Guerra com 8 filtros de validação e Top 3 estratégico.",
    category: "ideation",
    available: true,
  },
  {
    id: "high-ticket-ideas",
    name: "Ideias de Produto High Ticket",
    emoji: "🏆",
    role: "Estrategista de Ofertas Premium",
    description: "Transforma sua autoridade em 3 conceitos estratégicos de ofertas premium (high-ticket), com análise e recomendação da melhor oportunidade.",
    category: "ideation",
    available: true,
  },
  {
    id: "lead-magnet-ideas",
    name: "Ideias de Isca Digital",
    emoji: "🎣",
    role: "Especialista em Conceitos de Iscas de Alta Conversão",
    description: "Gera 10 conceitos de iscas digitais de alta conversão com análise estratégica e Top 3 recomendados.",
    category: "ideation",
    available: true,
  },
  {
    id: "big-ideas",
    name: "Big Ideas para Newsletter",
    emoji: "💡",
    role: "Especialista em Conceitos Memoráveis",
    description: "Transforma ideias brutas em big ideas estratégicas que geram impacto imediato e conexão emocional.",
    category: "ideation",
    available: true,
  },
  {
    id: "content-ideas",
    name: "Ideias de Conteúdos",
    emoji: "🧠",
    role: "Especialista em Ideação Estratégica de Conteúdo",
    description: "Cria ideias de conteúdo estratégicas para captação, consideração e conversão, combinando viralização e DNA de marca.",
    category: "ideation",
    available: true,
  },
  {
    id: "headlines",
    name: "Headlines (Títulos)",
    emoji: "🔥",
    role: "Especialista em Headlines de Alta Conversão",
    description: "Gera títulos irresistíveis para YouTube, Instagram, TikTok, LinkedIn, E-mails e mais — o elemento 20/80 de toda copy.",
    category: "ideation",
    available: true,
  },
  {
    id: "hooks",
    name: "Hooks",
    emoji: "🪝",
    role: "Especialista em Ganchos de Atenção",
    description: "Cria hooks de 6 segundos que garantem atenção máxima — virais, de anúncio e de vendas — para qualquer plataforma.",
    category: "ideation",
    available: true,
  },
  {
    id: "ad-angles",
    name: "Ângulos de Anúncios",
    emoji: "🎯",
    role: "Especialista em Ângulos Criativos",
    description: "Transforma um anúncio em 5 abordagens estratégicas únicas para maximizar performance no Meta Ads.",
    category: "ideation",
    available: true,
  },
  {
    id: "youtube-titles",
    name: "Ângulos e Títulos YouTube",
    emoji: "▶️",
    role: "Especialista em Títulos e CTR",
    description: "Gera ângulos, variações e títulos otimizados para maximizar CTR e performance no YouTube.",
    category: "ideation",
    available: true,
  },
  {
    id: "upsell-ideas",
    name: "Ideias de Upsell",
    emoji: "💎",
    role: "Estrategista de Upsells e AOV",
    description: "Gera conceitos de upsell estratégicos para aumentar o Valor Médio por Cliente (AOV) com plano de ação e análise de impacto.",
    category: "ideation",
    available: true,
  },
  {
    id: "competitor-analysis",
    name: "Análise de Concorrência",
    emoji: "🔎",
    role: "Analista de Inteligência Competitiva",
    description: "Recebe URL ou descrição de um concorrente e gera mapa comparativo com posicionamento, pontos fortes/fracos e oportunidades de diferenciação.",
    category: "ideation",
    available: true,
  },
  {
    id: "price-calculator",
    name: "Calculadora de Preço",
    emoji: "💲",
    role: "Estrategista de Pricing",
    description: "Ajuda a definir pricing estratégico baseado em valor percebido, concorrência e margem de lucro.",
    category: "ideation",
    available: true,
  },

  {
    id: "thank-you-page",
    name: "Página de Obrigado",
    emoji: "🎉",
    role: "Especialista em Páginas de Obrigado Pós-Compra",
    description: "Cria páginas de obrigado estratégicas que direcionam o cliente para o email de acesso e iniciam o relacionamento pós-compra.",
    category: "copywriting",
    available: true,
  },

  // sales-page moved to guided category
  {
    id: "vsl-writer",
    name: "Roteirista VSL",
    emoji: "🎬",
    role: "Especialista em Video Sales Letters",
    description: "Produz roteiros cinematográficos para VSLs de 15 a 60 minutos com gatilhos emocionais e estrutura narrativa.",
    category: "copywriting",
    available: true,
  },
  {
    id: "landing-page-copy",
    name: "Landing Pages",
    emoji: "🌐",
    role: "Especialista em Copy para Landing Pages",
    description: "Cria páginas de alta conversão com 13 blocos essenciais, do headline à FAQ, otimizadas para mobile e escaneabilidade.",
    category: "copywriting",
    available: true,
  },
  {
    id: "short-vsl",
    name: "Short VSL [1-3 Min]",
    emoji: "🎯",
    role: "Especialista em VSLs Curtas para Ads",
    description: "Cria roteiros de VSL curta (1-3 min) focados em ganchos e curiosidade, perfeitos para anúncios in-feed e aquecimento de audiência.",
    category: "copywriting",
    available: true,
  },
  {
    id: "mini-vsl",
    name: "Mini VSL [3-7 Min]",
    emoji: "⚡",
    role: "Especialista em VSLs Curtas de Alta Conversão",
    description: "Cria roteiros de Mini VSL (3-7 min) com múltiplos hooks, perfeitos para low-ticket, agendamentos e aquecimento de audiência.",
    category: "copywriting",
    available: true,
  },
  {
    id: "whatsapp-copy",
    name: "WhatsApp Copy",
    emoji: "💬",
    role: "Especialista em Sequências de WhatsApp",
    description: "Cria sequências de mensagens para WhatsApp — broadcast, atendimento, follow-up e recuperação de vendas — com tom conversacional e gatilhos de resposta.",
    category: "copywriting",
    available: true,
  },
  {
    id: "sales-script",
    name: "Script de Vendas",
    emoji: "📞",
    role: "Especialista em Scripts de Vendas Consultivas",
    description: "Cria roteiros para ligações e reuniões comerciais com objeções mapeadas, rebuttals e técnicas de fechamento.",
    category: "copywriting",
    available: true,
  },
  {
    id: "squeeze-page",
    name: "Página de Captura",
    emoji: "🧲",
    role: "Especialista em Squeeze Pages",
    description: "Cria copy específica para páginas de captura de leads (isca digital), com headline magnética, bullet points e CTA irresistível.",
    category: "copywriting",
    available: true,
  },
  {
    id: "email-sequence",
    name: "Estrategista de E-mails",
    emoji: "📧",
    role: "Especialista em Sequências de E-mail",
    description: "Cria sequências de e-mail automatizadas para nutrição, lançamento e recuperação de carrinho.",
    category: "copywriting",
    available: false,
  },
  {
    id: "email-subjects",
    name: "Assuntos de E-mails",
    emoji: "✉️",
    role: "Especialista em Títulos de E-mail",
    description: "Cria títulos de e-mail que disparam taxas de abertura com micro-histórias irresistíveis e preheaders estratégicos.",
    category: "copywriting",
    available: true,
  },
  {
    id: "email-generator",
    name: "Gerador de Email",
    emoji: "💌",
    role: "Especialista em E-mails de Marketing e Vendas",
    description: "Cria e-mails de alta conversão para recuperação de vendas, confirmação de compra e mais, com a voz da sua marca.",
    category: "copywriting",
    available: true,
  },
  {
    id: "ad-generator",
    name: "Gerador de Anúncios",
    emoji: "📣",
    role: "Especialista em Criação de Anúncios",
    description: "Transforma conteúdo em anúncios de alta conversão para Meta Ads usando templates estratégicos por estágio do funil.",
    category: "copywriting",
    available: true,
  },
  {
    id: "ad-funnel",
    name: "Funil de Anúncios",
    emoji: "🔻",
    role: "Especialista em Funil de Consciência",
    description: "Cria sequência completa de anúncios baseada nos 5 Níveis de Consciência de Schwartz, do insciente à conversão.",
    category: "copywriting",
    available: true,
  },
  {
    id: "content-to-ad",
    name: "Conteúdo em Anúncio",
    emoji: "📢",
    role: "Especialista em Conversão de Conteúdo para Ads",
    description: "Transforma conteúdo orgânico validado em anúncios de alta conversão para Meta Ads com 5 hooks testáveis.",
    category: "copywriting",
    available: true,
  },
  {
    id: "google-ads-search",
    name: "Google Ads Rede de Pesquisa",
    emoji: "🔎",
    role: "Especialista em Google Ads Search",
    description: "Cria 3 temas de campanha otimizados para Google Ads com títulos, descrições, palavras-chave e extensões prontos para uso.",
    category: "copywriting",
    available: true,
  },
  {
    id: "google-my-business",
    name: "Google Meu Negócio",
    emoji: "📍",
    role: "Especialista em Google Meu Negócio",
    description: "Otimiza perfis e cria conteúdo estratégico para Google Meu Negócio: posts, descrições, Q&A e respostas a avaliações.",
    category: "copywriting",
    available: true,
  },
  {
    id: "universal-adapter",
    name: "Adaptador Universal",
    emoji: "🔄",
    role: "Especialista em Replicação Estrutural",
    description: "Replica a arquitetura persuasiva de qualquer criativo validado, adaptando o conteúdo ao DNA da sua campanha.",
    category: "copywriting",
    available: true,
  },

  // ── Conteúdo & Social ──
  {
    id: "carousel-creator",
    name: "Designer de Carrosséis",
    emoji: "🎠",
    role: "Especialista em Conteúdo Visual",
    description: "Cria roteiros de carrosséis para Instagram e LinkedIn com hooks irresistíveis e CTAs de engajamento.",
    category: "content",
    available: true,
  },
  {
    id: "carousel-generator",
    name: "Gerador de Carrossel",
    emoji: "🎨",
    role: "Especialista em Carrosséis com Scripts Validados",
    description: "Transforma qualquer conteúdo em carrosséis envolventes usando scripts de conteúdo validados e adaptados ao estágio do funil.",
    category: "content",
    available: true,
  },
  {
    id: "post-captions",
    name: "Legendas para Posts",
    emoji: "📝",
    role: "Especialista em Legendas Estratégicas",
    description: "Cria legendas otimizadas para Instagram, TikTok e LinkedIn que maximizam engajamento e conversão.",
    category: "content",
    available: true,
  },
  {
    id: "video-script",
    name: "Roteiro de Vídeos Verticais",
    emoji: "🎥",
    role: "Especialista em Roteiros para Reels, Shorts e TikTok",
    description: "Transforma qualquer conteúdo em roteiros de alta performance para vídeos verticais, com 4 frameworks: Narrativa Viral, Engenharia Viral, Quebra de Mito e Lo-fi.",
    category: "content",
    available: true,
  },
  {
    id: "newsletter-writer",
    name: "Escritor de Newsletter",
    emoji: "📰",
    role: "Especialista em Storytelling para Newsletters",
    description: "Transforma ideias em narrativas longas e reflexivas para newsletters, com fluxo modular de Introdução, Desenvolvimento e Conclusão.",
    category: "content",
    available: true,
  },
  {
    id: "text-structure",
    name: "Estrutura de Textos Memoráveis",
    emoji: "🗺️",
    role: "Especialista em Estruturação Estratégica",
    description: "Usa o método GPS da Escrita para criar estruturas de texto poderosas, mapeando da conclusão ao título.",
    category: "content",
    available: true,
  },
  {
    id: "presentation-generator",
    name: "Gerador de Apresentação",
    emoji: "🎤",
    role: "Especialista em Apresentações Persuasivas",
    description: "Transforma ideias em roteiros completos de apresentação, slide a slide, para propostas comerciais, palestras e webinários.",
    category: "content",
    available: true,
  },
  {
    id: "twitter-content",
    name: "Conteúdo para Twitter/X",
    emoji: "𝕏",
    role: "Especialista em Conteúdo para Twitter/X",
    description: "Cria tweets, threads e frases que engajam, educam e vendem usando frameworks estratégicos por estágio de funil.",
    category: "content",
    available: true,
  },
  {
    id: "youtube-description",
    name: "Descrição YouTube",
    emoji: "📝",
    role: "Especialista em SEO para YouTube",
    description: "Cria descrições otimizadas para SEO que ajudam seus vídeos a ranquear melhor em buscas específicas no YouTube.",
    category: "content",
    available: true,
  },
  {
    id: "content-calendar",
    name: "Calendário de Conteúdo",
    emoji: "📅",
    role: "Especialista em Planejamento de Conteúdo",
    description: "Cria calendário estratégico com 15 posts conectados à jornada do cliente, equilibrando valor e conversão.",
    category: "content",
    available: true,
  },
  {
    id: "storytelling-adapter",
    name: "Adaptador de Storytelling",
    emoji: "📖",
    role: "Especialista em Narrativa Persuasiva",
    description: "Transforma qualquer conteúdo em uma narrativa mais poderosa usando frameworks clássicos de storytelling.",
    category: "content",
    available: true,
  },
  {
    id: "thread-generator",
    name: "Gerador de Threads",
    emoji: "🧵",
    role: "Especialista em Threads para LinkedIn e X",
    description: "Cria threads otimizadas para LinkedIn e Twitter/X com hooks sequenciais que mantêm o leitor até o final.",
    category: "content",
    available: true,
  },
  {
    id: "bio-link-copy",
    name: "Bio Link (Linktree Copy)",
    emoji: "🔗",
    role: "Especialista em Copy para Bio Links",
    description: "Cria textos estratégicos para cada link da bio (Linktree, Beacons, etc.) que maximizam cliques e conversão.",
    category: "content",
    available: true,
  },
  {
    id: "podcast-generator",
    name: "Gerador de Podcast",
    emoji: "🎙️",
    role: "Roteirista de Podcasts",
    description: "Cria roteiros para episódios de podcast com estrutura, perguntas para entrevistas e show notes otimizados.",
    category: "content",
    available: true,
  },
  {
    id: "comment-responses",
    name: "Respostas a Comentários",
    emoji: "💬",
    role: "Especialista em Engajamento Social",
    description: "Gera respostas estratégicas para comentários em posts — engajamento, quebra de objeções e direcionamento para vendas.",
    category: "content",
    available: true,
  },

  {
    id: "ad-intelligence",
    name: "Ad Intelligence",
    emoji: "🕵️",
    role: "Analista de Inteligência de Anúncios",
    description: "Analisa anúncios coletados e gera Scale Score, Offer Card estruturado e mapeamento de funil para cada criativo.",
    category: "products",
    available: true,
  },

  // ── Produtos & Ofertas ──
  {
    id: "low-ticket-product",
    name: "Gerador de Produto Low Ticket",
    emoji: "📦",
    role: "Arquiteto de Produtos Digitais Low Ticket",
    description: "Transforma ideias em produtos digitais low ticket completos e prontos para vender, com conteúdo principal e bônus estratégico.",
    category: "products",
    available: true,
  },
  {
    id: "high-ticket-product",
    name: "Gerador de Produto High Ticket",
    emoji: "🏆",
    role: "Arquiteto de Produtos High Ticket",
    description: "Transforma uma ideia de produto high ticket em um plano de entrega detalhado com método proprietário, estrutura e ecossistema de suporte.",
    category: "products",
    available: true,
  },
  {
    id: "offer-generator",
    name: "Gerador de Ofertas",
    emoji: "💰",
    role: "Especialista em Arquitetura de Ofertas",
    description: "Cria blueprints completos de ofertas irresistíveis com nomes magnéticos, bônus estratégicos, garantias e lógica de valor.",
    category: "products",
    available: true,
  },
  {
    id: "lead-magnet-generator",
    name: "Gerador de Isca Digital",
    emoji: "🧲",
    role: "Especialista em Criação de Iscas Digitais",
    description: "Transforma ideias em iscas digitais práticas (checklists, diagnósticos, scripts, templates, planos) que geram leads qualificados.",
    category: "products",
    available: true,
  },
  {
    id: "persuasive-premise",
    name: "Premissa Persuasiva",
    emoji: "💎",
    role: "Especialista em Premissa Única",
    description: "Define a única crença que, se aceita pelo cliente, torna a compra do seu produto o único caminho lógico.",
    category: "products",
    available: true,
  },
  {
    id: "unique-mechanism",
    name: "Mecanismo Único da Solução",
    emoji: "⚙️",
    role: "Especialista em Diferenciação Estratégica",
    description: "Cria 10 opções de mecanismo único que diferenciam sua solução de todos os concorrentes, usando justaposição contraditória e análise competitiva.",
    category: "products",
    available: true,
  },
  {
    id: "problem-mechanism",
    name: "Mecanismo Único do Problema",
    emoji: "🔬",
    role: "Especialista em Causa Surpreendente Principal",
    description: "Identifica e nomeia a causa raiz dos problemas do seu público (CSP) para criar um único ponto de crença que leva naturalmente à venda.",
    category: "products",
    available: true,
  },
  {
    id: "methodology",
    name: "Metodologia",
    emoji: "🧩",
    role: "Especialista em Estruturação de Métodos",
    description: "Transforma conhecimento disperso em metodologia proprietária memorável com nomenclatura única e estrutura pronta para produtos e cursos.",
    category: "products",
    available: true,
  },
  {
    id: "guarantee-generator",
    name: "Gerador de Garantia",
    emoji: "🛡️",
    role: "Especialista em Garantias Estratégicas",
    description: "Cria garantias estratégicas (incondicional, condicional, invertida) que eliminam risco e aumentam conversão.",
    category: "products",
    available: true,
  },
  {
    id: "value-stack",
    name: "Stack de Valor",
    emoji: "📊",
    role: "Especialista em Ancoragem de Valor",
    description: "Monta a apresentação do valor total da oferta (produto + bônus + garantia) com ancoragem de preço e lógica persuasiva.",
    category: "products",
    available: true,
  },
  {
    id: "testimonial-generator",
    name: "Gerador de Depoimentos",
    emoji: "⭐",
    role: "Especialista em Coleta de Depoimentos",
    description: "Cria templates e perguntas para coletar depoimentos poderosos de clientes — guia a coleta, não inventa.",
    category: "products",
    available: true,
  },

  {
    id: "brand-voice",
    name: "Arquiteto de Marca",
    emoji: "🎭",
    role: "Especialista em Tom de Voz",
    description: "Define o posicionamento, tom de voz e identidade verbal da marca com guidelines aplicáveis.",
    category: "branding",
    available: true,
  },
  {
    id: "offer-naming",
    name: "Nomes para Ofertas",
    emoji: "🏷️",
    role: "Especialista em Naming de Ofertas",
    description: "Cria nomes estratégicos para produtos, cursos e ofertas usando 6 categorias comprovadas de naming que aumentam conversão.",
    category: "branding",
    available: true,
  },
  {
    id: "high-value-compass",
    name: "Bússola do Cliente de Alto Valor",
    emoji: "🧭",
    role: "Especialista em Segmentação de Alto Ticket",
    description: "Identifica clientes ideais de alto valor usando a metodologia da bússola (6 direções) e o Axioma 41-39-20.",
    category: "branding",
    available: true,
  },
  {
    id: "writing-analysis",
    name: "Análise de Escrita",
    emoji: "🔍",
    role: "Especialista em Análise Estilística",
    description: "Decifra e replica qualquer estilo de escrita com precisão, revelando padrões de tom, estrutura e elementos distintivos.",
    category: "branding",
    available: true,
  },
  {
    id: "brand-manifesto",
    name: "Gerador de Manifesto",
    emoji: "📜",
    role: "Especialista em Manifestos de Marca",
    description: "Cria manifestos de marca que definem crenças, valores e posicionamento de forma emocional e memorável.",
    category: "branding",
    available: true,
  },
  {
    id: "tagline-generator",
    name: "Gerador de Tagline/Slogan",
    emoji: "💬",
    role: "Especialista em Slogans e Taglines",
    description: "Cria slogans e taglines usando fórmulas comprovadas de memorabilidade que fixam a marca na mente do público.",
    category: "branding",
    available: true,
  },
  {
    id: "brand-archetype",
    name: "Arquétipo de Marca",
    emoji: "🏛️",
    role: "Especialista em Arquétipos Jungianos",
    description: "Identifica o arquétipo Jungiano da marca e gera guidelines de comunicação baseadas nele para consistência narrativa.",
    category: "branding",
    available: true,
  },
  {
    id: "linkedin-optimizer",
    name: "Otimização de LinkedIn",
    emoji: "💼",
    role: "Especialista em Perfis Profissionais de LinkedIn",
    description: "Reescreve seu perfil do LinkedIn para gerar autoridade e atrair oportunidades, com diagnóstico completo, 3 opções de headline e seções otimizadas.",
    category: "branding",
    available: true,
  },
  {
    id: "seo-optimizer",
    name: "Otimizador de SEO",
    emoji: "🔎",
    role: "Especialista em SEO para Newsletters",
    description: "Otimiza newsletters para ranquear no Google com palavras-chave, slugs, títulos SEO e meta-descrições estratégicas.",
    category: "content",
    available: true,
  },
  {
    id: "instagram-profile",
    name: "Perfil do Instagram",
    emoji: "📸",
    role: "Especialista em Perfis de Instagram",
    description: "Cria perfis completos do Instagram: @, bio magnética, destaques persuasivos e posicionamento claro para atrair clientes ideais.",
    category: "branding",
    available: true,
  },
  {
    id: "buyer-profiles",
    name: "Perfis de Compra",
    emoji: "🧠",
    role: "Especialista em Arquétipos de Compra",
    description: "Mapeia arquétipos de compra com gatilhos, medos e conflitos internos que influenciam decisões — transformando tensões em persuasão.",
    category: "branding",
    available: true,
  },
  {
    id: "monetization-plan",
    name: "Plano de Monetização",
    emoji: "💸",
    role: "Estrategista de Monetização de Perfil",
    description: "Transforma engajamento em receita com auditoria de perfil, projeção financeira e plano de lançamento baseado em dados reais.",
    category: "ideation",
    available: true,
  },
  {
    id: "problem-promise",
    name: "Problema & Promessa",
    emoji: "🎯",
    role: "Especialista em Posicionamento Estratégico",
    description: "Define o problema específico e a promessa clara usando as metodologias D.O.R.E.S e M.O.E.D.A para criar posicionamentos magnéticos.",
    category: "products",
    available: true,
  },
  {
    id: "image-prompt",
    name: "Prompt para Imagens",
    emoji: "🖼️",
    role: "Especialista em Prompt Engineering para IA de Imagens",
    description: "Cria prompts técnicos para gerar imagens publicitárias em MidJourney, DALL·E, Stable Diffusion e outras ferramentas de IA.",
    category: "content",
    available: true,
  },
  {
    id: "monochrome-prompt",
    name: "Prompt para Imagens Monocromáticas",
    emoji: "🖤",
    role: "Diretor de Arte Monocromático",
    description: "Transforma conteúdo de newsletters e artigos em prompts detalhados para imagens monocromáticas com forte apelo visual e emocional.",
    category: "content",
    available: true,
  },
  {
    id: "unique-selling-proposition",
    name: "Proposta Única de Vendas",
    emoji: "⚡",
    role: "Especialista em PUV de Alto Impacto",
    description: "Transforma diferenciais do seu negócio em Propostas Únicas de Vendas claras e memoráveis usando fórmulas clássicas da publicidade.",
    category: "products",
    available: true,
  },
  {
    id: "marketing-xray",
    name: "Raio-X de Marketing",
    emoji: "🔬",
    role: "Analista de Estratégias de Comunicação",
    description: "Analisa qualquer conteúdo escrito revelando estratégias ocultas, técnicas persuasivas e estruturas replicáveis que fazem vender mais.",
    category: "ideation",
    available: true,
  },
  {
    id: "copy-reviewer-cub",
    name: "Revisor de Copy (CUB)",
    emoji: "🩺",
    role: "Consultor de Copywriting — Método CUB",
    description: "Analisa sua copy pelo método CUB (Confuso, Inacreditável, Chato) e entrega um plano de ação para transformá-la em versão de alta conversão.",
    category: "copywriting",
    available: true,
  },
  {
    id: "email-reviewer",
    name: "Revisor de E-mails",
    emoji: "📬",
    role: "Especialista em Revisão de E-mails e Newsletters",
    description: "Revisa e-mails e newsletters com sugestões 'antes → depois' para corrigir erros, melhorar fluidez e aumentar conversão.",
    category: "copywriting",
    available: true,
  },
  {
    id: "youtube-script",
    name: "Roteiro de YouTube",
    emoji: "🎬",
    role: "Roteirista Estratégico de YouTube",
    description: "Transforma qualquer ideia em roteiros completos para YouTube com frameworks narrativos validados, hooks, estrutura e CTAs.",
    category: "content",
    available: true,
  },
  {
    id: "spin-selling",
    name: "SPIN Selling",
    emoji: "🔄",
    role: "Especialista em Vendas Consultivas — Método SPIN",
    description: "Gera perguntas estratégicas nos 4 estágios do SPIN Selling (Situação, Problema, Implicação, Necessidade) para vendas complexas.",
    category: "products",
    available: true,
  },
  {
    id: "story-launch",
    name: "Story Launch de 14 Dias",
    emoji: "📲",
    role: "Estrategista de Lançamentos via Stories",
    description: "Cria sequências completas de stories do Instagram para lançamentos em 14 dias, do aquecimento ao fechamento do carrinho.",
    category: "content",
    available: true,
  },
  {
    id: "instagram-stories",
    name: "Story para Instagram",
    emoji: "📱",
    role: "Especialista em Stories de Alta Performance",
    description: "Cria sequências de stories para vendas ou construção de autoridade no Instagram, com hooks, CTAs e sugestões visuais.",
    category: "content",
    available: true,
  },
  {
    id: "youtube-thumbnails",
    name: "Thumbnails para YouTube",
    emoji: "🖼️",
    role: "Especialista em Thumbnails de Alto CTR",
    description: "Gera textos virais e conceitos visuais completos para thumbnails de YouTube que maximizam CTR mantendo autenticidade.",
    category: "content",
    available: true,
  },
  {
    id: "webinar-script",
    name: "Gerador de Webinar/Aula",
    emoji: "🎓",
    role: "Estrategista de Webinários e Aulas ao Vivo",
    description: "Estrutura roteiros completos para webinários de venda ou aulas gratuitas — com timestamps, sugestões de slides, CTAs estratégicos e momentos de interação.",
    category: "content",
    available: true,
  },
  {
    id: "brand-voice-extractor",
    name: "Voz do Autor/Marca",
    emoji: "🗣️",
    role: "Especialista em Extração de DNA de Voz",
    description: "Analisa textos autênticos para criar o DNA completo da voz de marca, com regras de adaptação para diferentes contextos de comunicação.",
    category: "branding",
    available: true,
  },
  {
    id: "quiz-generator",
    name: "Gerador de Quiz Interativo",
    emoji: "🧩",
    role: "Especialista em Quizzes de Engajamento e Conversão",
    description: "Cria quizzes interativos estratégicos que engajam o público, qualificam leads e direcionam para a compra do produto ideal.",
    category: "content",
    available: true,
  },
];
